version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    command: sh -c "mvn install -Dmaven.test.failure.ignore=true && cp -r /app/target/allure-results /app/target/surefire-reports /target/"
    volumes:
      - myapp-results:/target/allure-results
      - myapp-reports:/target/surefire-reports
  allure:
    image: "frankescobar/allure-docker-service"
    user: "1000:1000" # Используйте соответствующие значения UID и GID
    environment:
      CHECK_RESULTS_EVERY_SECONDS: None
      KEEP_HISTORY: 3
    ports:
      - "5050:5050"
    volumes:
      - myapp-results:/app/allure-results
      - myapp-reports:/app/default-reports
    depends_on:
      myapp:
        condition: service_completed_successfully

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://77.232.131.169:5050" # Убран лишний префикс "http://"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    depends_on:
      myapp:
        condition: service_completed_successfully

volumes:
  myapp-results: # Создание объема
  myapp-reports: # Создание объема для хранения отчетов