version: '3'
services:
  stellarburgertestapi:
    build: .
    command: mvn clean test
  allure:
    image: frankescobar/allure-docker-service    # Официальный образ Allure
    ports:
      - "8081:8081"  # Порт для отчетов Allure
    volumes:
      - ./allure-results:/app/allure-results  # Монтируем директорию с результатами тестов
