version: '3'
services:
  myapp:
    build: .
    tty: true
  allure:
    image: "frankescobar/allure-docker-service"
    user: 1000:1000
    environment:
      CHECK_RESULTS_EVERY_SECONDS: None
      KEEP_HISTORY: 5
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
