version: '3'
services:
  stellarburgertestapi:
    build: .
    ports:
      - "8080:8080"
    command: sh -c "mvn clean test && allure generate target/allure-results --clean -o target/allure-report && allure serve target/allure-report"
    volumes:
      - ./allure-results:/app/target/allure-results