version: '3'
services:
  stellarburgertestapi:
    build: .
    ports:
      - "8080:8080"  # Порт, на котором ваше приложение работает

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"  # Порт для доступа к отчету Allure
    volumes:
      - ./allure-results:/app/target/allure-results  # Монтируем директорию с результатами тестов
    depends_on:
      - stellarburgertestapi